import assert from "node:assert/strict";
import test from "node:test";
import { isProtectedStockMovement } from "../../lib/stock-movement-policy.ts";

test("protects stock movements generated by sales", () => {
  assert.equal(
    isProtectedStockMovement({ reason: "Venta CREDIT", note: null }),
    true,
  );
  assert.equal(
    isProtectedStockMovement({
      reason: "Venta desde pedido confirmado",
      note: null,
    }),
    true,
  );
  assert.equal(
    isProtectedStockMovement({
      reason: "Inventario reservado por separado",
      note: "Venta abc123",
    }),
    true,
  );
});

test("protects returns and administrative corrections with or without accents", () => {
  assert.equal(
    isProtectedStockMovement({
      reason: "Devolución por eliminación de venta",
      note: null,
    }),
    true,
  );
  assert.equal(
    isProtectedStockMovement({
      reason: "Corrección de movimiento",
      note: "Se corrigió el movimiento anterior",
    }),
    true,
  );
});

test("keeps manually registered inventory movements manageable", () => {
  assert.equal(
    isProtectedStockMovement({
      reason: "Compra nueva",
      note: "Mercancía recibida en bodega",
    }),
    false,
  );
  assert.equal(
    isProtectedStockMovement({ reason: "Ajuste", note: null }),
    false,
  );
  assert.equal(
    isProtectedStockMovement({
      reason: "Salida manual",
      note: "Venta registrada por el administrador",
    }),
    false,
  );
});
